### ISSUE TITLE
Feature Request: Auto-add LIMIT 1 to queryFirstRow()

### ISSUE THREAD

**Issue by danielscsc** [SergeyTsalkov/meekrodb#104]
**Feature Request: Automatic 'LIMIT 1' for `queryFirstRow()`**

### Description
The idea is to automatically append a 'LIMIT 1' clause to the query when using `queryFirstRow()`. Including 'LIMIT 1' in the query serves as a best practice to optimize performance when the application expects only a single result, preventing unnecessary data retrieval and processing.

### Reasoning
When fetching just one row from the database, it is a common practice to use the 'LIMIT 1' clause in the SQL query. However, adding this clause manually every time can be error-prone and adds unnecessary verbosity to the code. This feature would automate the process.

### Implementation Options
A potential implementation option is an object-level setting on the MeekroDB object itself. This setting, such as `setLimitOneDefault()`, would control the automatic addition of 'LIMIT 1' for all subsequent `queryFirstRow` calls on that instance:  
```php
DB::setLimitOneDefault(true); //just an example name...    
DB::queryFirstRow("SELECT * FROM table WHERE condition");
```

Another potential implementation is to add it as a pre_run hook.  Is there a way to only use the hook when using `queryFirstRow()`?  I guess I can do something as follows, but feels a bit much (especially if running queryFirstRow() multiple times in a single script):
```php
DB::addHook('pre_run', function ($q) {
  $trace = debug_backtrace();
  $fromFirstRow = array_filter($trace, function ($stack) {
    return isset($stack['function']) && $stack['function'] == 'queryFirstRow';
  });
  
  if ($fromFirstRow) {
    $q['query'] .= ' LIMIT 1';
  }

  return $q['query'];
});
```

As far as how to inject the 'LIMIT 1' itself, I assume you can simply add it to the end of the query. I do see in the MySQL docs for [5.7](https://dev.mysql.com/doc/refman/5.7/en/select.html) and [8.0](https://dev.mysql.com/doc/refman/8.0/en/select.html) that other directives can appear after a LIMIT, I'm not sure we need to code against that (similar to checking for existing LIMIT's, see notes below).  If the "limit 1 by default" feature is enabled, the responsibility lies with the user to use it appropriately.

### Notes
1.  I apologize for not providing a pull request for this, I wasn't sure about the best way to go about it.  You're the expert here :)
2.  When (if) implementing this feature, there's no need to include safeguards in the code to check for the presence of an existing 'LIMIT' clause. Responsibility for ensuring query cleanliness remains with the consumer. 

Thanks again for this wonderful tool!

**Comment by SergeyTsalkov** [comment]
I'd prefer not to do this because, like you said, "LIMIT 1" is not always the last thing in a SELECT query. For example, you can use row-level locking within a transaction by adding "FOR UPDATE" after the LIMIT. Also, what happens if you enable setLimitOneDefault(true) and then it turns out some of the queries within your program already have the LIMIT 1? They'd get it twice now, breaking the query.

An alternative approach might be to generate a warning if queryFirstRow() gets more than one row, so we let the programmer know that they should fix their query by adding "LIMIT 1" manually. For example, we might throw a MeekroDBWarningException that says "queryFirstRow() got back 10,000 rows, shouldn't you add LIMIT 1?" Then the programmer could either fix their query, or set `DB::$silenceWarnings = true;`

If you really want the behavior you described, the pre_run hook seems like a good way to get it. I could probably make things easier on you by letting the hooks know what the calling function was, so you don't have to do a backtrace.

**Comment by danielscsc** [comment]
>I could probably make things easier on you by letting the hooks know what the calling function was, so you don't have to do a backtrace.

If you can do that, that would be great!  Thanks!

**Comment by SergeyTsalkov** [comment]
Adding this is actually more complicated than I thought. I'm still planning to do this, but to be honest I don't know when.

**Comment by SergeyTsalkov** [comment]
This is resolved in the new v3 release. Please see hooks documentation on the website for more.
