### ISSUE TITLE
On the design

### ISSUE THREAD

**Issue by colshrapnel** [SergeyTsalkov/meekrodb#69]
Not really an issue but just random thoughts.

After all those years, do you still call MeekroDB "simple"?   
Don't you think that due to some architectural decisions, the library become a bit overcomplicated?

Say, there are *four* distinct functions for INSERT. And still some cases are not covered (such as INSERT DELAYED). And do you really need any of them, given there is already a %ll placeholder?    
Or *five* error handlers. Seriously? Do you really need that much? How much of them have *any* use, especially given there is usually a *site-wide* error handler and all you really need is throw_exception_on_error?

verticalSlice() and reIndex() are just more complicated versions of PHP's internal array_column()

And what are your thoughts on the naming? As a complete stranger to this lib, I cannot make *any* sense from the names:

- queryFirstRow() - oh, thats an assoc array, as opposed to the conventional "row" which stands for the enumerated array in mysqli
- queryFirstList() - really, can't get what it should be. List usually stands for multiple results but here it's about the first one. Ah, that's what usually called a "row"
- queryFirstColumn() - it's just the first result, just like in the FirstRow, right? Oh no. It's multiple results
- queryOneColumn() - wait, didn't we have it already? What's the point in selecting multiple columns but fetching only one?
- queryFirstField() / queryOneField() - same as above
- queryRaw() - everywhere it stands for the raw SQL, not a raw *result*.

You would say it's nitpicking but I would say non-intuitive function names are bad for usability. That counts against the simplicity. 

Don't get me wrong, I love the core functionality, the original idea of customized placeholders is brilliant, makes many queries indeed 100 times simpler. And I would have recommended this library, if not the things mentioned above. 

Is there a chance you would reconsider the architecture, making this library more lightweight and flexible? Just to run a query and get the result? Where the result is represented by *another class*, just like it's done in PDO/mysqli?

And in case you would decide to add some fancy helpers, like a full-featured query builder, it would be a *completely different class* that uses this one as a driver?

**Comment by SergeyTsalkov** [comment]
Hello! I really appreciate your thoughts and I've been thinking about creating a more modern version of this library. I'd love to tell you about that and get your thoughts.

But first, could I ask about your own library? I see you made safemysql, which was heavily influenced by meekrodb. You're saying my function names are unclear, but I think yours aren't really better. getCol() vs queryFirstColumn(), getRow() vs queryFirstRow(), getOne() vs queryFirstField() etc. I guess it's a matter of taste?

Regarding queryRaw(), you say that it stands for raw queries and not raw results everywhere. Could you show me some examples from the PDO or mysqli documentation to support that? I actually just looked, and I can't find any.

One big difference is that your getAll() is like my query(), and your query() is like my queryRaw(). My justification is, I don't think you need the mysqli object very often. I really only included queryRaw() because some people were trying to return huge result sets that would overflow memory. mysqli_result uses a pointer that can scroll through the results one by one without loading them all into memory.

You're right that verticalSlice() is literally just array_column(), but reIndex() is different and I think covers a use case that I haven't seen done anywhere else. If you grab some output with query(), you'll get back an array of assoc arrays. reIndex() will replace the keys in that array so you can instantly search through it without having to loop over the whole thing every time. However, my current docs don't even mention these functions because I don't feel they're relevant in 2020. They'll probably be removed in the redesign.

I think you're right that  should be dropped.

Here's what I see coming out of a redesign:
1. Simplified error handling. All errors throw an exception, and the exception will have variables that tell you what query caused it and what the problem was.

2. Wrapping PDO instead of mysqli. That way, we get support for other databases like sqlite.

3. Changing the `%` variable character to `:` so you have `:s` instead of `%s` and so on. I originally used `%` because anyone who's used printf() would be familiar with `%s` and such, but it turns out that this interferes with MySQL's DATE_FORMAT() which considers `%` a meaningful character.

4. Drop these functions: queryOneColumn(), queryOneField(), queryFirstList()

Now if I understand you correctly, the part of this library that you like is the single-line query builder. So one thing that would address your needs would be a DB::parse() function that builds and returns a complete, fully escaped query string. You could then run that query in mysqli or PDO, which is what you seem to prefer. You could ignore the rest of the library, just pretend it doesn't exist. It'd work roughly like this:

```
$PdoStatement = $Pdo->query(DB::parse("SELECT * FROM tbl WHERE name=%s", 'Joe'));
```

Would that work for you?

**Comment by colshrapnel** [comment]
safemysql was [inspired by Nikita Popov](https://github.com/nikic/DB) when he was fifteen :)
And this my project is long abandoned, because now I see its fallacies. 

The idea is quite popular though, there are many libraries using the same approach.

Regarding raw queries, that's a common notion related to database wrappers, not drivers. See [here](https://stackoverflow.com/questions/22925451/how-can-i-query-raw-via-eloquent) or [here](https://stackoverflow.com/questions/3325012/execute-raw-sql-using-doctrine-2) for example.

My bad,  reIndex() cannot be replaced by array_column().  But if you decide to switch to PDO, it will become unnecessary, as PDO already has such modes out of the box. 

Also, regarding PDO, be ready that people would demand _named placeholders_ support and hence you will need something like `lb:columns`.  (The format is taken from https://github.com/gajus/doll  and it seems quite natural).

But it's all just insignificant details compared to the last suggestion you made! Ironically, I didn't realize it myself until I saw your code. Indeed that's what I had in mind but didn't fully realize that - a separate parser! Given it can create a correctly formatted SQL, you can use it then with any driver of choice - be it mysqli, or PDO, or MeekroDB or Eloquent or whatever!

There is a problem though - if you start with PDO, you will need a way to tell the parser what SQL flavor it needs to use, especially regarding escaping identifiers. And of course the actual driver-specific escapeIdentifier() method, that would escape column and table names  according to specific database rules, like 

    function escapeIdentifier($field){
        return "`".str_replace("`", "``", $field)."`";
    }

for mysql    
as far as I can tell, such escaping should be a bullet-proof solution even in regard of security, making it possible to use `%b` without much fear. 

And then indeed I would use it with PDO, as its fluent interface will suit all needs, like

    $data = $Pdo->query(DB::parse("SELECT * FROM tbl WHERE name=%s", 'Joe'))->fetchAll(PDO::FETCH_UNIQUE);

which will be the same as using reIndex();

The only my concern in passing variables as is. It proved to be inconvenient. So instead of passing separate variables, I would rather pass them as array. With short array syntax it won't be a problem to type but it will be much more convenient when used in a function where you don't know beforehand which variables will be used. Also, it will allow extra parameters such as flags or so

    $sql = DB::parse("SELECT * FROM accounts WHERE type = %s AND age > %i", [$type, 15], SOME_FLAG);

**Comment by SergeyTsalkov** [comment]
When I say "switch to PDO as a backend", I just mean use it to run the queries we generate. The switch would be transparent to the user, except that the library would (mostly) work with sqlite and other databases. You're right that it wouldn't work perfectly, though: other databases might use different identifier formats, and wouldn't have things like REPLACE INTO (which is a mysql-specific feature) so DB::replace() wouldn't work. But it would mostly work.

Regarding the escapeIdentifier, we actually do what you say already. I'm still pretty sure that it's not secure enough-- if you haven't already, you should read up on how incomplete unicode characters can be used to break escaping and inject code. It's subtle and nasty. The %b is mostly fine, but if I was using it with user-supplied data, I would make sure to use preg_replace() to strip it down to [a-z0-9] first.

Regarding named placeholders, we have that already. See the docs for more.

I really like the doll format you showed, but switching formats is super-tricky because lots of people are already using this library in their projects and would have to change lots of code. I really like PHP's culture of never breaking backwards compatibility, and will try to stick to it for as long as I can.

I'll plan to expose DB::parse() very soon, but keep in mind that it'll still require MeekroDB to be connected to the database you're using in order to work correctly. You see, it relies on mysqli_real_escape_string() which has to be aware of your database connection (and its default encoding) in order to work correctly. Otherwise people can use broken unicode characters to bypass your escaping and inject code.

Regarding passing the the variables as an array, I can do that. I'll have to detect whether you're doing that so the old method keeps working, too.

**Comment by Weshley** [comment]
Greetings SergeyTsalkov!

Long time listener, first time caller....

I'm glad to hear there are plans for a revised/updated iteration of this lib... I've been HAPPILY using it for years in all the places it makes sense (php+sql data stores) and have been able to sleep well at night.

As a performance freak... I have to ask if you've ever considered turning this lib into a compiled module? I haven't done any kind of analysis on your code (interpreted vs compiled) however with the low frequency of required changes (i.e. code stability) and utilization of something like [Zephir](https://zephir-lang.com/en)... it may not be that daunting of a task to convert to a compiled module...

2 Pennies and food for thought.

Best wishes!

**Comment by SergeyTsalkov** [comment]
Hey @Weshley I'm glad you like it! This library is definitely not dead, I still use it daily for multiple projects. I think of it as pretty much finished though. I did just do a moderate-size cleanup release, please check out the announcement on github and let me know what you think! Regarding doing it as a compiled module, I honestly don't think there are any speed gains to be had here. Probably 99%+ of execution will be spent waiting for MySQL in any non-trivial app.

**Comment by SergeyTsalkov** [comment]
The new version features `DB::parse()`, which satisfies the request in this issue. Closing.
