### ISSUE TITLE
how to add hook?

### ISSUE THREAD

**Issue by stefanak-michal** [SergeyTsalkov/meekrodb#72]
Hi.

I'm currently looking on your changes after those many years and major change for me is different approach for success handler. I see you are talking about hooks but methods about hooks in DB class are private. Is it a mistake? Or there is a way how to set hook which I don't see?

https://github.com/SergeyTsalkov/meekrodb/blob/master/db.class.php#L178

**Comment by stefanak-michal** [comment]
sorry. I see it now. You have magic method there and you can call it only through static. that's unfortunate.

**Comment by SergeyTsalkov** [comment]
If the success handler approach worked for you, you can just keep running the old version of MeekroDB-- it still works!

The methods you use to manage hooks are addHook(), removeHook(), and removeHooks(). These methods are not private, why do you think they are? Also, these methods can be used through either static or object usage (just like any other methods in MeekroDB). For example:

```
DB::addHook('post_run', function() { echo 'You ran a query!'; });
$db->addHook('post_run', function() { echo 'You ran a query!'; });
```

See the docs on hooks: https://meekro.com/docs/hooks.html
.. and the docs on using MeekroDB with objects instead of static methods: https://meekro.com/docs/static-vs-object.html

**Comment by stefanak-michal** [comment]
I didn't know if you omit method visibility in php is public by default. I'm used from C# where default is private. In php I'm used to explicitly say what visibility it has everytime.
