### ISSUE TITLE
Why is there only a queryFirstRow and not a queryLastRow

### ISSUE THREAD

**Issue by Friends4U** [SergeyTsalkov/meekrodb#75]
I need the latest record, queryLastRow would be perfect for that but it's not included, why is that?

**Comment by Friends4U** [comment]
I can fox it by using:  "ORDER BY orderdate DESC" but I wuld have liked the queryLastRow option :)

**Comment by SergeyTsalkov** [comment]
I would prefer not to have that because it encourages transferring too much data from the database. It's fastest to only transfer the rows you care about, so queryFirstRow should be used with "ORDER BY whatever LIMIT 1" so you only get the one row you're going to look at. If you want the last row instead, just switch the direction of the ORDER BY.

**Comment by Friends4U** [comment]
Tnx :)
