### ISSUE TITLE
Cast row to class

### ISSUE THREAD

**Issue by JmzTaylor** [SergeyTsalkov/meekrodb#91]
Is it possible to cast results to a cast automatically?  Obviously I can do

```
$row = DB::queryFirstRow('SELECT * FROM users WHERE id=%i', $id);
$myVar = new myClass($row['id'], $row['name'], $row['phone']);
```

But was just wondering if there was an easier way to do it, especially when there is a lot of columns.  

Thanks for the great library btw.

**Comment by wadih** [comment]
Not that I know of. 

I think actually your above syntax is already good, it fits on one line, it's expressive in the sense that it's easy to understand what it's doing, and it's linear. I wouldn't try to change it, I think that would be overautomation, when it starts hurting rather than helping. I think you're at the sweet spot right now. The wiring of the arguments somehow has to be done.

Though your question reminded me of a keyword in the PHP language that might interest you perhaps for other needs, that is [list](https://www.php.net/manual/en/function.list.php). Actually it's being used a lot in meekro's source code, you could look at how it's being used there. It would still require at least one line to do the argument wiring, as per above. I personally haven't been using it, didn't need it so far. 

Hope it helps!

**Comment by stefanak-michal** [comment]
What about array unpack?
```php
$myVar = new myClass(...$row);
```

**Comment by Nrde** [comment]
I don't think it works with string keyed arrays. Support is only in PHP 8.1+ I think.

**Comment by JmzTaylor** [comment]
> Not that I know of.
> 
> I think actually your above syntax is already good, it fits on one line, it's expressive in the sense that it's easy to understand what it's doing, and it's linear. I wouldn't try to change it, I think that would be overautomation, when it starts hurting rather than helping. I think you're at the sweet spot right now. The wiring of the arguments somehow has to be done.
> 
> Though your question reminded me of a keyword in the PHP language that might interest you perhaps for other needs, that is [list](https://www.php.net/manual/en/function.list.php). Actually it's being used a lot in meekro's source code, you could look at how it's being used there. It would still require at least one line to do the argument wiring, as per above. I personally haven't been using it, didn't need it so far.
> 
> Hope it helps!

Yeah that was just a short example.  But when it has many fields the code gets ugly quick.  Its PHP so I can only hope for so much :)

**Comment by stefanak-michal** [comment]
> I don't think it works with string keyed arrays. Support is only in PHP 8.1+ I think.

You can do ...array_values($row)

**Comment by JmzTaylor** [comment]
> > I don't think it works with string keyed arrays. Support is only in PHP 8.1+ I think.
> 
> You can do ...array_values($row)

array unpack worked perfectly.  Learned something new.  One key note to this is constructor needs to match the order of the DB columns.
