### ISSUE TITLE
DB::queryFirstRow returning null when direct command show records - closed without resolution

### ISSUE THREAD

**Issue by Dinosane2** [SergeyTsalkov/meekrodb#99]
Issue #97 was closed in record time with no resolution at all. You guys have no obligation to fix or even answer issues, but closing existing issues keep unknown bugs to those who are willing to use your nice code. Thank you for it, btw ! I´ll try to fix and do a PR ...

**Comment by SergeyTsalkov** [comment]
You've given me nothing to fix. Saying "queryFirstRow doesn't work" is not helpful because it does work for thousands of other users, and in our own testing system. You need to offer a self-contained example that works on a clean VPS with PHP+MySQL installed. Other people need to be able to run your self-contained example and produce the same results. If you can do that, please reopen the other issue and I'll look closer.
